// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: advanced_features/calculator/calculatorpb/calculatorpb.proto

package calculatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Salute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *Salute) Reset() {
	*x = Salute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Salute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salute) ProtoMessage() {}

func (x *Salute) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salute.ProtoReflect.Descriptor instead.
func (*Salute) Descriptor() ([]byte, []int) {
	return file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{0}
}

func (x *Salute) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Salute) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type SquareRootRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *SquareRootRequest) Reset() {
	*x = SquareRootRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareRootRequest) ProtoMessage() {}

func (x *SquareRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareRootRequest.ProtoReflect.Descriptor instead.
func (*SquareRootRequest) Descriptor() ([]byte, []int) {
	return file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{1}
}

func (x *SquareRootRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type SquareRootResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberRoot float64 `protobuf:"fixed64,1,opt,name=number_root,json=numberRoot,proto3" json:"number_root,omitempty"`
}

func (x *SquareRootResponse) Reset() {
	*x = SquareRootResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareRootResponse) ProtoMessage() {}

func (x *SquareRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareRootResponse.ProtoReflect.Descriptor instead.
func (*SquareRootResponse) Descriptor() ([]byte, []int) {
	return file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{2}
}

func (x *SquareRootResponse) GetNumberRoot() float64 {
	if x != nil {
		return x.NumberRoot
	}
	return 0
}

type SaluteWithDeadlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Salute *Salute `protobuf:"bytes,1,opt,name=salute,proto3" json:"salute,omitempty"`
}

func (x *SaluteWithDeadlineRequest) Reset() {
	*x = SaluteWithDeadlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaluteWithDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaluteWithDeadlineRequest) ProtoMessage() {}

func (x *SaluteWithDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaluteWithDeadlineRequest.ProtoReflect.Descriptor instead.
func (*SaluteWithDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{3}
}

func (x *SaluteWithDeadlineRequest) GetSalute() *Salute {
	if x != nil {
		return x.Salute
	}
	return nil
}

type SaluteWithDeadlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SaluteWithDeadlineResponse) Reset() {
	*x = SaluteWithDeadlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaluteWithDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaluteWithDeadlineResponse) ProtoMessage() {}

func (x *SaluteWithDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaluteWithDeadlineResponse.ProtoReflect.Descriptor instead.
func (*SaluteWithDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{4}
}

func (x *SaluteWithDeadlineResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_advanced_features_calculator_calculatorpb_calculatorpb_proto protoreflect.FileDescriptor

var file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x44, 0x0a, 0x06, 0x53, 0x61,
	0x6c, 0x75, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x2b, 0x0a, 0x11, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x35, 0x0a,
	0x12, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72, 0x6f,
	0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x6f, 0x6f, 0x74, 0x22, 0x47, 0x0a, 0x19, 0x53, 0x61, 0x6c, 0x75, 0x74, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x61, 0x6c, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53,
	0x61, 0x6c, 0x75, 0x74, 0x65, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x75, 0x74, 0x65, 0x22, 0x38, 0x0a,
	0x1a, 0x53, 0x61, 0x6c, 0x75, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc7, 0x01, 0x0a, 0x0f, 0x41, 0x64, 0x76, 0x61,
	0x6e, 0x63, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x53,
	0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1d, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x12, 0x53, 0x61,
	0x6c, 0x75, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x25, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x61,
	0x6c, 0x75, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x61, 0x6c, 0x75, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x44,
	0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescOnce sync.Once
	file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescData = file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDesc
)

func file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescGZIP() []byte {
	file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescOnce.Do(func() {
		file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescData)
	})
	return file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDescData
}

var file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_advanced_features_calculator_calculatorpb_calculatorpb_proto_goTypes = []interface{}{
	(*Salute)(nil),                     // 0: calculator.Salute
	(*SquareRootRequest)(nil),          // 1: calculator.SquareRootRequest
	(*SquareRootResponse)(nil),         // 2: calculator.SquareRootResponse
	(*SaluteWithDeadlineRequest)(nil),  // 3: calculator.SaluteWithDeadlineRequest
	(*SaluteWithDeadlineResponse)(nil), // 4: calculator.SaluteWithDeadlineResponse
}
var file_advanced_features_calculator_calculatorpb_calculatorpb_proto_depIdxs = []int32{
	0, // 0: calculator.SaluteWithDeadlineRequest.salute:type_name -> calculator.Salute
	1, // 1: calculator.AdvancedService.SquareRoot:input_type -> calculator.SquareRootRequest
	3, // 2: calculator.AdvancedService.SaluteWithDeadline:input_type -> calculator.SaluteWithDeadlineRequest
	2, // 3: calculator.AdvancedService.SquareRoot:output_type -> calculator.SquareRootResponse
	4, // 4: calculator.AdvancedService.SaluteWithDeadline:output_type -> calculator.SaluteWithDeadlineResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_advanced_features_calculator_calculatorpb_calculatorpb_proto_init() }
func file_advanced_features_calculator_calculatorpb_calculatorpb_proto_init() {
	if File_advanced_features_calculator_calculatorpb_calculatorpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Salute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareRootRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareRootResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaluteWithDeadlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaluteWithDeadlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_advanced_features_calculator_calculatorpb_calculatorpb_proto_goTypes,
		DependencyIndexes: file_advanced_features_calculator_calculatorpb_calculatorpb_proto_depIdxs,
		MessageInfos:      file_advanced_features_calculator_calculatorpb_calculatorpb_proto_msgTypes,
	}.Build()
	File_advanced_features_calculator_calculatorpb_calculatorpb_proto = out.File
	file_advanced_features_calculator_calculatorpb_calculatorpb_proto_rawDesc = nil
	file_advanced_features_calculator_calculatorpb_calculatorpb_proto_goTypes = nil
	file_advanced_features_calculator_calculatorpb_calculatorpb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdvancedServiceClient is the client API for AdvancedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdvancedServiceClient interface {
	//*
	// Error handling
	// this RPC will thrown an error if the number sent is negative
	// the error being sent is of type INVALID_ARGUMENT
	SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error)
	SaluteWithDeadline(ctx context.Context, in *SaluteWithDeadlineRequest, opts ...grpc.CallOption) (*SaluteWithDeadlineResponse, error)
}

type advancedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdvancedServiceClient(cc grpc.ClientConnInterface) AdvancedServiceClient {
	return &advancedServiceClient{cc}
}

func (c *advancedServiceClient) SquareRoot(ctx context.Context, in *SquareRootRequest, opts ...grpc.CallOption) (*SquareRootResponse, error) {
	out := new(SquareRootResponse)
	err := c.cc.Invoke(ctx, "/calculator.AdvancedService/SquareRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advancedServiceClient) SaluteWithDeadline(ctx context.Context, in *SaluteWithDeadlineRequest, opts ...grpc.CallOption) (*SaluteWithDeadlineResponse, error) {
	out := new(SaluteWithDeadlineResponse)
	err := c.cc.Invoke(ctx, "/calculator.AdvancedService/SaluteWithDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdvancedServiceServer is the server API for AdvancedService service.
type AdvancedServiceServer interface {
	//*
	// Error handling
	// this RPC will thrown an error if the number sent is negative
	// the error being sent is of type INVALID_ARGUMENT
	SquareRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error)
	SaluteWithDeadline(context.Context, *SaluteWithDeadlineRequest) (*SaluteWithDeadlineResponse, error)
}

// UnimplementedAdvancedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdvancedServiceServer struct {
}

func (*UnimplementedAdvancedServiceServer) SquareRoot(context.Context, *SquareRootRequest) (*SquareRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SquareRoot not implemented")
}
func (*UnimplementedAdvancedServiceServer) SaluteWithDeadline(context.Context, *SaluteWithDeadlineRequest) (*SaluteWithDeadlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaluteWithDeadline not implemented")
}

func RegisterAdvancedServiceServer(s *grpc.Server, srv AdvancedServiceServer) {
	s.RegisterService(&_AdvancedService_serviceDesc, srv)
}

func _AdvancedService_SquareRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SquareRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvancedServiceServer).SquareRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.AdvancedService/SquareRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvancedServiceServer).SquareRoot(ctx, req.(*SquareRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvancedService_SaluteWithDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaluteWithDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvancedServiceServer).SaluteWithDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.AdvancedService/SaluteWithDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvancedServiceServer).SaluteWithDeadline(ctx, req.(*SaluteWithDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdvancedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.AdvancedService",
	HandlerType: (*AdvancedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SquareRoot",
			Handler:    _AdvancedService_SquareRoot_Handler,
		},
		{
			MethodName: "SaluteWithDeadline",
			Handler:    _AdvancedService_SaluteWithDeadline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "advanced_features/calculator/calculatorpb/calculatorpb.proto",
}
